version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - bash codebuild/npm_configure.sh
  build:
    commands:
      - echo Build started on `date`
      - echo Running Twine.js build script
      - bash codebuild/build_packages.sh
  post_build:
    commands:
      - echo Build completed on `date`
