name: Build

on:
  push:
    branches: [ lerna-test ]

env:
  CANONICAL_APP_NAME: twine.js

jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

      # Setup

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Publish App
        run: |
          ci/npm_configure.sh && \
          ci/build_packages.sh
        env:
          NEXUS_NAME: AO Service Account
          NEXUS_EMAIL: PSNApplicationOperations@inmar.com
          NPM_TOKEN: ${{ secrets.ERETAIL_NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.ERETAIL_PACKAGES_TOKEN }}
